service: tf-lambda

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
    slim: true
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - s3transfer
      - setuptools
      - six
      - tensorboard

provider:
  name: aws
  stackName: tf-lambda
  runtime: python3.7
  region: us-east-1
  stage: dev

functions:
  python37-memory-1536:
    name: tf-lambda-1536
    description: tensorflow function 1536mb
    runtime: python3.7
    handler: lambda.lambda_handler
    memorySize: 1536
